configName: sam_rh71_ek
folderName: sam_rh71_ek
format_version: v1.0
frameworkPath: ..\..\..
processor: ATSAMRH71F20C
projectName: tcpip_udp_client_server_sam_rh71_ek
settings:
  PackageFilter: bsp;core;crypto;csp;dev_packs;net;net_apps_sam_rh71
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAMRH71_DFP\2.3.124\samrh71c\atdf\ATSAMRH71F20C.atdf
