format_version: v1.0
type: UniqueComponent
attributes: {id: drvExtPhyKsz8061}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: DRV_ETHPHY_MAC_NAME}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvExtPhyKsz8061, value: GMAC}
  - type: Integer
    attributes: {id: TCPIP_INTMAC_PHY_ADDRESS}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '4'}
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: libdrvExtPhyKsz8061}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: drvGmac}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: GMAC_PHY_Dependency}
- type: ElementPosition
  attributes: {x: '21', y: '73', id: drvExtPhyKsz8061}
